# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "configs/**"
      - "yarn.lock"
      - ".github/workflows/release.yml"

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Generate Token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.TOKEN_APP_ID }}
          private_key: ${{ secrets.TOKEN_APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Install
        run: yarn
      - name: Release
        uses: ridedott/release-me-action@v3
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          dry-run: false
          release-rules: |
            [
              { "release": "patch", "type": "build" },
              { "release": "patch", "type": "ci" },
              { "release": "patch", "type": "chore" },
              { "release": "patch", "type": "improvement" },
              { "release": "patch", "type": "refactor" },
              { "release": false, "subject": "*\\[skip release\\]*" }
            ]
      - name: Npm Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish